version: "3.9"

services:
  twitch-checker:
    image: twitch-username-availability:latest
    container_name: twitch-username-availability
    restart: unless-stopped
    env_file:
      - stack.env
    volumes:
      - ./cron-logs:/var/log
      - ./screenshots:/app/screenshots
