version: "3.9"

services:
  twitch-checker:
    container_name: twitch-username-checker
    build:
      context: .
      dockerfile: Dockerfile
    image: twitch-username-checker:latest
    restart: unless-stopped
    env_file:
      - .env
    working_dir: /app
    volumes:
      - ./cron-logs:/var/log
      - ./screenshots:/app/screenshots
